project:
  type: website

website:
  title: "Home"
  sidebar:
    logo: logo.png
  page-footer:
    center: 
      - text: "Special thanks to Michelle Borgers for designing the I4 logo, and to Pratyaksh Singh & Elina Koivisto for providing the banner image"

format:
  html:

    grid:
      sidebar-width: 300px
    link-external-newwindow: true
    link-external-icon: true
    theme:
      - cosmo
      - styles.css
    mainfont: "Gill Sans, sans-serif"
    body-width: "90%"
    toc: true
    toc-location: left
    toc-title: "Jump to"
  