project:
  type: website

website:
  title: "i4 conference"
  sidebar:
    logo: logo.jpg

format:
  html:
    theme:
      - cosmo
      - styles.css
    mainfont: "Gill Sans, sans-serif"
    body-width: "90%"
    toc: true
    toc-location: left
    toc-title: "Jump to"